variables:
  GO3_PUSH_PUBLIC_KEY: "BPFYs2UAvISg3gPmcRHnZMSxOMvwjm6fPl_wgD2hnpYvaJEO54M-4ymsE5mA9zGrVxT0wcpD-M2S-xj04UQUe3I"

stages:
  - test
  - deploy

build:
  image: "node:8"
  script:
    - make release
  stage: test
  artifacts:
    paths:
      - dist/
      - locales/
      - index.html
      - server/

test:
  image: "node:8"
  script:
    - make test
  stage: test

lint:
  image: "node:8"
  script:
    - make lint
  stage: test

deploy:
  image: "base/archlinux:latest"
  before_script:
    - pacman -Sy --noconfirm ansible git openssh python3 rsync
    - mkdir ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - cd deploy
    - ansible-playbook go3.yml --extra-vars push_key=$PUSH_KEY
  dependencies:
    - build
  stage: deploy
  when: manual
