stages:
  - test
  - deploy

build:
  image: "node:8"
  script:
    - make release
  stage: test
  artifacts:
    paths:
      - dist/
      - locales/
      - index.html
      - server/

test:
  image: "node:8"
  script:
    - make test
  stage: test

lint:
  image: "node:8"
  script:
    - make lint
  stage: test
