stages:
  - test

build:
  image: "node:7"
  script:
    - make release
  stage: test
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
      - locales/
      - index.html

test:
  image: "node:7"
  script:
    - make test
  stage: test
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - node_modules/

lint:
  image: "node:7"
  script:
    - make lint
  stage: test
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - node_modules/
