stages:
  - test
  - deploy

build:
  image: "node:8"
  script:
    - make release
  stage: test
  artifacts:
    paths:
      - dist/
      - locales/
      - index.html

test:
  image: "node:8"
  script:
    - make test
  stage: test

lint:
  image: "node:8"
  script:
    - make lint
  stage: test

deploy:
  image: "alpine:3.5"
  before_script:
    - apk --update add ansible git openssh python py2-pip rsync
    - mkdir ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - cd deploy
    - ansible-playbook go3.yml
  dependencies:
    - build
  stage: deploy
  when: manual
  only:
    - master
